# Generated by Django 4.2 on 2024-11-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="avatars/default_avatar.jpg",
                upload_to="avatars/",
                verbose_name="Аватар",
            ),
        ),
    ]
